plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "."

[build.environment]

[build.processing]

[build.processing.css]
bundle = true
minify = true

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[build.processing.js]
bundle = true
minify = true

[build.services]